### ISSUE TITLE
Scoring reviews

### ISSUE THREAD

**Issue by enazario11** [FlukeAndFeather/openbiologging#10]
For reviews that summarize a few different technologies (e.g., Nowacek et al., 2016), should these each be listed as an additional data type with respective FAIR scoring? Or, for review articles, should the focus be on bio-logging devices (and their sections) alone? 

Thanks!!

Emily

**Comment by FlukeAndFeather** [comment]
We're limiting the rubric to newly collected biologging data. So for the Nowacek paper, they're reviewing practices, not presenting new data. So it's NA for device type etc.
