### ISSUE TITLE
intro feedback :)

### ISSUE THREAD

**Issue by cmhale98** [FlukeAndFeather/openbiologging#13]
Hi Max :)

With respect to Note 2 ("Is this excessive? I want to introduce the FAIR principles explicitly, but we only have 500 words for the intro and we’re already over.") I think it is excessive (even though I like the way you explain it) only bc it cuts into our word count and I'm assuming readers either 1) know what FAIR is/means or 2) can go look at Wilkinson et al.'s paper. Maybe we can direct people directly to Box 2 of that paper? Maybe if we create a figure we can create something that allows us to explain FAIR in our terms but also frees up some space?

I think (depending on the word count) after the hypothesis we should say something about what we expect our results to mean for the community. We say what we are going to do and what we mean but I don't think we have made clear what the impact of our findings is. I know we do not yet have results but we can project our goals...right?

**Comment by cmhale98** [comment]
Separate issue that I am not sure if others are having but when I recreated my review_assignment sheet all of the DOI's and associated info for each paper is shifted down one row so everything is one off. I'm not sure what to do about it.  Is it an easy fix? If not I can just ignore it and I'll be fine but if it is and it will mess things up in the future I figured I should mention it! Thanks Max :)

**Comment by FlukeAndFeather** [comment]
Thanks for the feedback, Conner! I agree with your ideas for the intro. I'm thinking of replacing the bullet points with a table. 

Good catch with the shifted DOIs. Emily noticed that too. Somehow one of the paper id's got duplicated and shifted everything down one. I went through and fixed them - let me know if your workbook still looks wrong.
