### ISSUE TITLE
Target journal?

### ISSUE THREAD

**Issue by FlukeAndFeather** [FlukeAndFeather/openbiologging#8]
Please share your thoughts re: target journals for submission

@rachelbuxton suggested choosing journals that score highly for open science practices e.g. PLOS and Peer J. Can you say more about how journals are assessed? Is there a list we can refer to?

@domroche suggested a [pre-registered report at Nature Eco Evo](https://www.nature.com/natecolevol/submission-guidelines/registeredreports).

@allisonpayne suggested Proc B's [Biological Science Practices](https://royalsocietypublishing.org/rspb/biological-science-practices) article type

**Comment by RachelBuxton** [comment]
Hi all,

Here's a database of FAO practices ranked for each journal: https://cor-p.shinyapps.io/EP_database/

(it comes from this pub: Veríssimo D, Pienkowski T, Arias M, Cugnière L, Doughty H, Hazenbosch M, de Lange E, Moskeland A, Grace M. Ethical Publishing in Biodiversity Conservation Science. Conservat Soc 2020;18:220-5
http://www.conservationandsociety.org/article.asp?issn=0972-4923;year=2020;volume=18;issue=3;spage=220;epage=225;aulast=Ver%EDssimo)

Journals like Biology Letters and PLOS One have high FOA rankings and relatively high IF

**Comment by FlukeAndFeather** [comment]
We've decided to submit a registered report to Nature Eco Evo
